# Generated by Django 5.0.7 on 2024-07-09 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(db_column='idServicio', primary_key=True, serialize=False)),
                ('precio', models.CharField(default=None, max_length=10, null=True)),
                ('imagen', models.ImageField(null='media/default.png', upload_to='servicio/')),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
